### ISSUE TITLE
Ubuntu 22.04 doesn't support being installed from ISO under Heads from exfat partition

### ISSUE THREAD

**Issue by tlaurion** [Nitrokey/ubuntu-oem#12]
22.04 simply didn't have exfat support under initramfs. Therefore user cannot use the self-created USB thumb drive's Public partition made a OEM factory reset/Re-Ownership to store ubuntu iso and detach sign it to boot from it.

Bumping to latest ubuntu ISO version would fix this.

**Comment by nestire** [comment]
-fixed with 24.04 version
